require:
  - rubocop-rspec
  - rubocop-performance

inherit_from:
  - https://raw.githubusercontent.com/webtranslateit/webtranslateit/main/.rubocop_common.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - lib/generators/**/*

RSpec/MultipleExpectations:
  Max: 3

inherit_mode:
   merge:
     - Exclude
